DROP FUNCTION IF EXISTS @extschema@.__CDB_FS_Name_Pattern();
DROP FUNCTION IF EXISTS @extschema@.__CDB_FS_Generate_Server_Name(TEXT, BOOL);
DROP FUNCTION IF EXISTS @extschema@.__CDB_FS_Extract_Server_Name(NAME);
DROP FUNCTION IF EXISTS @extschema@.__CDB_FS_Generate_Schema_Name(NAME, TEXT);
DROP FUNCTION IF EXISTS @extschema@.__CDB_FS_Generate_Server_Role_Name(NAME);
DROP FUNCTION IF EXISTS @extschema@.__CDB_FS_Create_Schema(NAME, TEXT);
DROP FUNCTION IF EXISTS @extschema@.__CDB_FS_server_type(NAME);
DROP FUNCTION IF EXISTS @extschema@.__CDB_FS_credentials_to_user_mapping(JSONB);
DROP FUNCTION IF EXISTS @extschema@.__CDB_FS_add_default_options(jsonb);
DROP FUNCTION IF EXISTS @extschema@.__CDB_FS_get_usermapping_username(NAME);
DROP FUNCTION IF EXISTS @extschema@.CDB_Federated_Server_Register_PG(TEXT, JSONB);
DROP FUNCTION IF EXISTS @extschema@.CDB_Federated_Server_Unregister(TEXT);
DROP FUNCTION IF EXISTS @extschema@.CDB_Federated_Server_List_Servers(TEXT);
DROP FUNCTION IF EXISTS @extschema@.CDB_Federated_Server_Grant_Access(TEXT, NAME);
DROP FUNCTION IF EXISTS @extschema@.CDB_Federated_Server_Revoke_Access(TEXT, NAME);
